/**
 * The vocabulary of the problem, and nothing else.
 *
 * This file — like everything under src/domain — must not import Node, Electron,
 * React or any adapter. The rule is enforced by tests/architecture.test.ts.
 */

export type FileKind = 'audio' | 'image'

/** A story already installed by Telmi-Sync in its own library. */
export interface LocalStory {
  /** Directory name, as generated by Telmi-Sync. De facto identifier. */
  directory: string
  title: string
  /** Carried over verbatim into a store entry: it identifies the story. */
  uuid: string
  /** Integer >= 1. At 0 or absent, Telmi-Sync never offers an update. */
  version: number
  minAge: number
  category: string
  description: string
  bytes: number
  fileCount: number
}

/**
 * A file the contributor explicitly picked.
 *
 * The `id` is a capability: it is the only thing handed to the interface, which
 * can display or play the file through it but never learns its path, and cannot
 * name a file that was not picked.
 */
export interface PickedFile {
  id: string
  name: string
  bytes: number
  from: 'disk' | 'url'
  /** Set when `from === 'url'`, so it can be shown and fetched again. */
  url?: string
}

export interface Chapter {
  /** Stable across reordering. */
  key: string
  /** Becomes the spoken title. Pre-filled from the file name. */
  title: string
  audio: PickedFile
  /** Seconds. Null while still unknown. */
  duration: number | null
  /** Optional: the cover is used instead. */
  image: PickedFile | null
}

export type RightsStatus =
  | 'own-work'
  | 'public-domain'
  | 'cc-by'
  | 'cc-by-sa'
  | 'written-permission'

export interface Rights {
  status: RightsStatus | ''
  source: string
  declaredBy: string
}

/** A story being prepared, before it becomes a pack and an entry. */
export interface Submission {
  title: string
  minAge: number
  category: string
  language: string
  description: string
  /** The menu question, spoken before the list of chapters. */
  question: string
  cover: PickedFile | null
  chapters: Chapter[]
  rights: Rights
}

/** Where the pack of a published story lives. The store hosts none of them. */
export type PackLocation =
  | { kind: 'release'; repo: string; tag: string; file: string; sha256: string; bytes: number }
  | { kind: 'external'; url: string; sha256: string; bytes: number }
  | { kind: 'repo-archive'; repo: string; branch?: string; sha256: string; bytes: number }

/** What is versioned in a store repository, and reviewed on moderation. */
export interface StoreEntry {
  slug: string
  title: string
  minAge: number
  category: string
  language: string
  description: string
  uuid: string
  version: number
  rights: { status: RightsStatus; source: string; declaredBy: string }
  pack: PackLocation
}
