/** Domain types, shared by the main process and the interface. */

/** A story already installed by Telmi-Sync in ~/.telmi/stories. */
export interface LocalStory {
  /** Directory name, as generated by Telmi-Sync. De facto identifier. */
  directory: string
  title: string
  /** Must be carried over verbatim into the entry: it identifies the story. */
  uuid: string
  /** Integer >= 1. At 0 or absent, Telmi-Sync never offers an update. */
  version: number
  minAge: number
  category: string
  description: string
  /** Bytes. Determines where the pack can be hosted. */
  bytes: number
  fileCount: number
}

export type FileKind = 'audio' | 'image'

/**
 * A file the contributor explicitly picked. The interface never sees its
 * contents: it gets an `id` that lets it display or play the file through the
 * `telmi-file://` protocol, while the main process keeps the path.
 */
export interface PickedFile {
  id: string
  name: string
  bytes: number
  from: 'disk' | 'url'
  /** Set when `from === 'url'`, so it can be shown and fetched again. */
  url?: string
}

export interface Chapter {
  /** Stable on the interface side, for reordering. */
  key: string
  /** Becomes the spoken title. Pre-filled from the file name. */
  title: string
  audio: PickedFile
  /** Seconds, measured by the interface through an <audio> element. */
  duration: number | null
  /** Optional: the cover is used instead. */
  image: PickedFile | null
}

export type RightsStatus =
  | 'own-work'
  | 'public-domain'
  | 'cc-by'
  | 'cc-by-sa'
  | 'written-permission'

export interface Rights {
  status: RightsStatus | ''
  source: string
  declaredBy: string
}

/** The full state of the submission screen. */
export interface Submission {
  title: string
  minAge: number
  category: string
  language: string
  description: string
  /** The menu question, spoken before the list of chapters. */
  question: string
  cover: PickedFile | null
  chapters: Chapter[]
  rights: Rights
}

/** Where to find the pack of a published story. The store hosts none of them. */
export type PackLocation =
  | { kind: 'release'; repo: string; tag: string; file: string; sha256: string; bytes: number }
  | { kind: 'external'; url: string; sha256: string; bytes: number }
  | { kind: 'repo-archive'; repo: string; branch?: string; sha256: string; bytes: number }

/** An entry: what is versioned in the store repository, and reviewed on moderation. */
export interface StoreEntry {
  slug: string
  title: string
  minAge: number
  category: string
  language: string
  description: string
  uuid: string
  version: number
  rights: { status: RightsStatus; source: string; declaredBy: string }
  pack: PackLocation
}
